project:
  type: website

website:
  title: "Pedalogical Developer Docs"
  repo-url: "https://github.com/wu-software-lab/AiTutor"
  repo-actions: [edit, issue]
  navbar:
    left:
      - text: "New Dev Setup"
        href: new-dev-setup.qmd
      - text: "DB Migration"
        href: migration.qmd
      - text: "Conventions (TBD)"

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
